ARTIFACT_SERVER_URL: http://localhost:8082/artifactory
ARTIFACT_REPO_NAME: libs-snapshot-local
ARTIFACT_LOC:com/durgasoft/weshopify-platform-app
ARTIFACT_VERSION=0.0.1-SNAPSHOT/

ARTIFACT_REPO_URL=$ARTIFACT_SERVER_URL/$ARTIFACT_REPO_NAME/$ARTIFACT_LOC/$ARTIFACT_VERSION

ARTIFACT_META_XML=maven-metadata.xml

ARTIFACTORY_USER=admin
ARTIFACTORY_PASSWORD=E1891@Urja
ARTIFACT_NAME=weshopify-platform-app

ARTIFACT_VERSION_WITH_TIME_STAMP=$(curl -u $ARTIFACTORY_USER:ARTIFACTORY_PASSWORD $ARTIFACT_REPO_URL/$ARTIFACT_META_XML | grep '<value>'| head -1 | sed "s/.*<value>\([^<]*\)<\/value>.*/\1/")

FINAL_ARTIFACT_URL=$ARTIFACT_REPO_URL/$ARTIFACT_NAME-$ARTIFACT_VERSION_WITH_TIME_STAMP.jar

wget --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD $FINAL_ARTIFACT_URL 
cp $ARTIFACT_NAME=$ARTIFACT_VERSION_WITH_TIME_STAMP.jar $ARTIFACT_NAME.jar

rm $ARTIFACT_NAME=$ARTIFACT_VERSION_WITH_TIME_STAMP.jar
